In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
dataset = pd.read_csv('/Users/Naila/Documents/Datasets/NLP/Review.csv')
dataset

sentiment                                             review
0     Negative  I had no background knowledge of this movie be...
1     Negative  I am a huge Jane Austen fan and I ordered the ...
2     Negative  Nothing to say but Wow! Has anyone actually ha...
3     Negative  i like Jane Austin novels. I love Pride and Pr...
4     Negative  In this day and age of incredible special movi...
...        ...                                                ...
9995  Positive  I first saw this movie back in the early'90's ...
9996  Positive  NYC, 2022: The Greenhouse effect, vanished oce...
9997  Positive  Those individuals familiar with Asian cinema, ...
9998  Positive  The kids, aged 7 to 14, got such a huge kick o...
9999  Positive  I so love this movie! The animation is great (...

[10000 rows x 2 columns]

In [50]:
dataset.sentiment.unique()

array(['Negative', 'Positive'], dtype=object)

In [51]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset.sentiment=le.fit_transform(dataset.sentiment)
dataset

sentiment                                             review
0             0  I had no background knowledge of this movie be...
1             0  I am a huge Jane Austen fan and I ordered the ...
2             0  Nothing to say but Wow! Has anyone actually ha...
3             0  i like Jane Austin novels. I love Pride and Pr...
4             0  In this day and age of incredible special movi...
...         ...                                                ...
9995          1  I first saw this movie back in the early'90's ...
9996          1  NYC, 2022: The Greenhouse effect, vanished oce...
9997          1  Those individuals familiar with Asian cinema, ...
9998          1  The kids, aged 7 to 14, got such a huge kick o...
9999          1  I so love this movie! The animation is great (...

[10000 rows x 2 columns]

## Cleaning the texts

In [57]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 10000):
    review = re.sub('[^a-zA-Z]', ' ', dataset['review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /Users/Naila/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## Creating the Bag of Words model

In [71]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 33900)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 0].values

In [72]:
len(X[0])

33900

In [59]:
y

array([0, 0, 0, ..., 1, 1, 1])

## Splitting the dataset into the Training set and Test set

In [60]:
X.shape

(10000, 1500)

In [61]:
y.shape

(10000,)

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [64]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## Training the Naive Bayes model on the Training set

In [74]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

## Predicting the Test set results

In [75]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 0]
 ...
 [0 1]
 [0 0]
 [0 1]]


## Confusion Matrix

In [76]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[782 219]
 [482 517]]


0.6495